Repository telbby/telbby-backend, pull requests merged in 2021-12, with the labels that each got.

#21 service에서 project로 테이블 네이밍 변경
  src/api/index.ts
  src/api/routes/projects/index.ts
  src/api/routes/projects/projects.controller.ts
  src/api/routes/services/index.ts
  src/api/validation/projects.ts
  src/constants/project.ts
  src/entity/chatroom.ts
  src/entity/project.ts
  src/entity/review.ts
  src/repositories/project.ts
  src/repositories/service.ts
  src/services/project.ts
  src/types/project.ts
  src/types/service.ts
  src/utils/project.ts
Labels: refactor, database

#26 Projects API Route URI 개선
  src/api/routes/projects/index.ts
Labels: refactor

#24 회원가입 validator 버그 수정
  .eslintrc
  src/utils/validation.ts
  tests/utils/validation.test.ts
Labels: bug

#28 telbby/validation 모듈을 사용하도록 개선
  .prettierrc
  package.json
  src/api/validation/users.ts
  src/constants/users.ts
  src/utils/validation.ts
  tests/utils/validation.test.ts
  yarn.lock
Labels: bug, refactor

#29 12주차 sprint merge
  .eslintrc
  .prettierrc
  package.json
  src/api/index.ts
  src/api/routes/projects/index.ts
  src/api/routes/projects/projects.controller.ts
  src/api/routes/services/index.ts
  src/api/validation/projects.ts
  src/api/validation/users.ts
  src/constants/project.ts
  src/constants/users.ts
  src/entity/chatroom.ts
  src/entity/project.ts
  src/entity/review.ts
  src/repositories/project.ts
  src/repositories/service.ts
  src/services/project.ts
  src/types/project.ts
  src/types/service.ts
  src/utils/project.ts
  src/utils/validation.ts
  tests/utils/validation.test.ts
  yarn.lock
Labels: sprint-complete
