Repository telbby/telbby-backend, pull requests merged in 2021-11, with the labels that each got.

#5 인증 관련 API 구현
  .mock.env
  ormconfig.ts
  package.json
  src/api/middlewares/error.ts
  src/api/routes/auth/auth.controller.ts
  src/api/routes/auth/index.ts
  src/api/routes/users/index.ts
  src/api/routes/users/users.controller.ts
  src/api/validation/auth.ts
  src/api/validation/user.ts
  src/api/validation/users.ts
  src/app.ts
  src/config/index.ts
  src/constants/auth.ts
  src/constants/users.ts
  src/entity/user.ts
  src/helpers/jwt.ts
  src/loaders/connect.ts
  src/loaders/dependency-injector.ts
  src/loaders/entity-injector.ts
  src/loaders/express.ts
  src/loaders/helper-injector.ts
  src/loaders/index.ts
  src/repositories/user.ts
  src/services/auth.ts
  src/services/user.ts
  src/types/index.ts
  src/utils/hash.ts
  src/utils/jwt.ts
  tests/helpers/jwt.test.ts
  tests/sample.test.ts
  tests/sample.ts
  tests/utils/hash.test.ts
  tests/utils/jwt.test.ts
  yarn.lock
Labels: feature

#11 회원가입 사용자 정보 validation 추가
  src/api/validation/users.ts
  src/constants/users.ts
  src/utils/validation.ts
  tests/utils/validation.test.ts
Labels: feature

#10 Database ERD 및 entity 추가
  src/entity/chat.ts
  src/entity/chatroom.ts
  src/entity/review.ts
  src/entity/service.ts
  src/entity/theme.ts
  src/entity/user.ts
Labels: feature, database

#15 5주차 sprint merge
  .eslintrc
  README.md
  ormconfig.ts
  package.json
  src/entity/chat.ts
  src/entity/chatroom.ts
  src/entity/review.ts
  src/entity/service.ts
  src/entity/theme.ts
  src/entity/user.ts
  tsconfig.json
Labels: sprint-complete

#16 서비스 관련 API 구현
  src/api/index.ts
  src/api/middlewares/validate-token.ts
  src/api/routes/auth/auth.controller.ts
  src/api/routes/services/index.ts
  src/api/routes/services/services.controller.ts
  src/api/validation/services.ts
  src/constants/error.ts
  src/entity/service.ts
  src/entity/theme.ts
  src/helpers/jwt.ts
  src/loaders/connect.ts
  src/repositories/service.ts
  src/repositories/theme.ts
  src/services/service.ts
  src/types/index.ts
  src/types/service.ts
  src/utils/jwt.ts
  src/utils/service.ts
  tests/helpers/jwt.test.ts
  tests/utils/jwt.test.ts
Labels: feature

#17 서비스 수정 API 구현
  .mock.env
  package.json
  src/api/routes/services/index.ts
  src/api/routes/services/services.controller.ts
  src/api/validation/services.ts
  src/config/index.ts
  src/constants/error.ts
  src/constants/service.ts
  src/repositories/service.ts
  src/services/service.ts
  src/types/service.ts
  src/utils/cloudinary.ts
  yarn.lock
Labels: feature

#19 7주차 sprint merge
  .mock.env
  package.json
  src/api/index.ts
  src/api/middlewares/validate-token.ts
  src/api/routes/auth/auth.controller.ts
  src/api/routes/services/index.ts
  src/api/routes/services/services.controller.ts
  src/api/validation/services.ts
  src/config/index.ts
  src/constants/error.ts
  src/constants/service.ts
  src/entity/service.ts
  src/entity/theme.ts
  src/helpers/jwt.ts
  src/loaders/connect.ts
  src/repositories/service.ts
  src/repositories/theme.ts
  src/services/service.ts
  src/types/index.ts
  src/types/service.ts
  src/utils/cloudinary.ts
  src/utils/jwt.ts
  src/utils/service.ts
  tests/helpers/jwt.test.ts
  tests/utils/jwt.test.ts
  yarn.lock
Labels: sprint-complete
